[build]
  publish = "."
  command = ""
  
# Force static site deployment
[build.processing]
  skip_processing = true

# Explicitly disable the Next.js plugin that's enabled in UI
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"


