[build]
  # Pure static site - serve files from root directory
  publish = "."
  # No build command needed for static HTML
  command = "echo 'Static site - no build needed'"

# Disable all plugins including Next.js auto-detection
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    disable = true

# Force static site deployment - skip all processing
[build.processing]
  skip_processing = true

# Disable framework detection
[build.environment]
  NODE_VERSION = "22"
  NETLIFY_USE_YARN = "false"
  NETLIFY_USE_NPM = "false"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"


