[build]
  # Static site - publish from public/ directory
  publish = "public"
  # No build command needed
  command = ""

[build.environment]
  # Skip Next.js plugin completely
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"


