[build]
  # Pure static site - serve files from root directory
  publish = "."
  # No build command needed for static HTML
  command = ""

# Force static site deployment - skip all processing
[build.processing]
  skip_processing = true

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"


